server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: ${sky.datasource.driver-class-name}
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 连接池的最小空闲数量
      min-idle: 5
      # 连接池最大连接数量
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
  data:
    redis:
      host: 192.168.229.101
      port: 6379
      database: 1

#mybatis:
#  #mapper配置文件
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.sky.entity
#  configuration:
#    #开启驼峰命名
#    map-underscore-to-camel-case: true

#用于打印框架生成的sql语句，便于调试
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


minio:
  url: http://192.168.229.101:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: sky


logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 2592000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: itheima
    user-ttl: 2592000000
    user-token-name: authentication
  wechat:
    appid: wxe7145237cb41d1e3
    secret: 07f21a5f525db08f19c5c6ef0efeb736
